# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    golang: "1.19"  # needed by hugo
  commands:
    # Full cusotmized build process
    # https://docs.readthedocs.io/en/stable/build-customization.html#override-the-build-process
    - curl -sSL https://github.com/gohugoio/hugo/releases/download/v0.111.3/hugo_extended_0.111.3_Linux-64bit.tar.gz | tar zxvf - hugo
    - sed -i "s#https://seismo-learn.org/links/#${READTHEDOCS_CANONICAL_URL}#" config.toml
    - ./hugo
    - mv public $READTHEDOCS_OUTPUT/html/
