name: Check Links

on:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # 403: Forbidden
          args: >-
            --accept 403
            --root-dir "${{ github.workspace }}"
            --verbose
            --no-progress
            --retry-wait-time 2
            --max-retries 2
            --timeout 20
            './**/*.md'
            './**/*.html'
            './**/*.yaml'
            './**/*.yml'
          fail: false
          jobSummary: true

      - name: Create issue
        if: steps.lychee.outputs.exit_code != 0
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh issue create --title "Broken links report ($(date -u +%Y-%m-%d))" --body-file ./lychee/out.md
